import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

import { getBundle, getShippingMethod, parseAmount, STRIPE_PRODUCT_NAMES } from "./offer";

const STRIPE_API = "https://api.stripe.com/v1";
const CURRENCY = "gbp";

const inputSchema = z.object({
  pack: z.string().min(1),
  shipping: z.string().min(1).nullish(),

  // UUID generated by Supabase for checkout_orders.id
  checkoutId: z.string().uuid().optional(),
});

export const createStripePaymentIntent = createServerFn({
  method: "POST",
})
  .inputValidator((data: unknown) => inputSchema.parse(data))
  .handler(async ({ data }) => {
    const secretKey = process.env["STRIPE_SECRET_KEY"];
    const publishableKey = process.env["STRIPE_PUBLISHABLE_KEY"];

    if (!secretKey || !publishableKey) {
      return {
        ok: false as const,
        error: "Stripe is not configured yet. Please add the Stripe keys.",
      };
    }

    /*
     * IMPORTANT:
     * The amount is calculated here on the server.
     * The browser never decides how much Stripe charges.
     */
    const bundle = getBundle(data.pack);
    const shipping = getShippingMethod(data.shipping);

    const amount = Math.round(parseAmount(bundle.price) * 100) + Math.round((shipping?.amount ?? 0) * 100);

    const form = new URLSearchParams();

    form.set("amount", String(amount));
    form.set("currency", CURRENCY);
    form.set("payment_method_types[0]", "card");

    form.set("description", STRIPE_PRODUCT_NAMES[bundle.id] ?? bundle.title);

    /*
     * Only technical/order-reference data goes to Stripe.
     *
     * No customer name, address, phone or delivery
     * information is stored in Stripe metadata.
     */
    form.set("metadata[pack]", bundle.id);

    if (data.checkoutId) {
      form.set("metadata[checkout_id]", data.checkoutId);
    }

    try {
      const res = await fetch(`${STRIPE_API}/payment_intents`, {
        method: "POST",

        headers: {
          Authorization: `Bearer ${secretKey}`,
          "Content-Type": "application/x-www-form-urlencoded",

          "Idempotency-Key": crypto.randomUUID(),
        },

        body: form.toString(),
      });

      const intent = (await res.json()) as {
        id?: string;
        client_secret?: string;

        error?: {
          message?: string;
        };
      };

      if (!res.ok || !intent.client_secret || !intent.id) {
        console.error("Stripe payment intent failed", res.status, intent);

        return {
          ok: false as const,

          error: intent.error?.message ?? "Could not start the payment.",
        };
      }

      return {
        ok: true as const,

        paymentIntentId: intent.id,
        clientSecret: intent.client_secret,
        publishableKey,
        amount,
      };
    } catch (error) {
      console.error(error);

      return {
        ok: false as const,

        error: "Payment service unavailable. Please try again.",
      };
    }
  });

/*
 * Associates an already-created PaymentIntent with the
 * checkout_orders record created in Supabase.
 *
 * Only the checkout UUID is sent to Stripe.
 */
const attachCheckoutSchema = z.object({
  clientSecret: z.string().min(1),
  checkoutId: z.string().uuid(),
});

export const attachCheckoutToPaymentIntent = createServerFn({
  method: "POST",
})
  .inputValidator((data: unknown) => attachCheckoutSchema.parse(data))
  .handler(async ({ data }) => {
    const secretKey = process.env["STRIPE_SECRET_KEY"];

    if (!secretKey) {
      return {
        ok: false as const,
        error: "Stripe is not configured.",
      };
    }

    /*
     * Stripe client secrets look like:
     *
     * pi_xxxxx_secret_xxxxx
     *
     * We only need the pi_xxxxx portion on the server.
     */
    const paymentIntentId = data.clientSecret.split("_secret_")[0];

    if (!paymentIntentId || !paymentIntentId.startsWith("pi_")) {
      return {
        ok: false as const,
        error: "Invalid PaymentIntent.",
      };
    }

    const form = new URLSearchParams();

    form.set("metadata[checkout_id]", data.checkoutId);

    try {
      const res = await fetch(`${STRIPE_API}/payment_intents/${paymentIntentId}`, {
        method: "POST",

        headers: {
          Authorization: `Bearer ${secretKey}`,
          "Content-Type": "application/x-www-form-urlencoded",
        },

        body: form.toString(),
      });

      const intent = (await res.json()) as {
        id?: string;

        error?: {
          message?: string;
        };
      };

      if (!res.ok) {
        console.error("Stripe PaymentIntent update failed", res.status, intent);

        return {
          ok: false as const,

          error: intent.error?.message ?? "Could not prepare the payment.",
        };
      }

      return {
        ok: true as const,
        paymentIntentId,
      };
    } catch (error) {
      console.error(error);

      return {
        ok: false as const,
        error: "Could not prepare the payment.",
      };
    }
  });
