/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ApiWhopTestRouteImport } from './routes/api/whop-test'
import { Route as ApiPublicUtmifyStripeRouteImport } from './routes/api/public/utmify-stripe'
import { Route as ApiPublicWhopWebhookRouteImport } from './routes/api/public/whop-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhopTestRoute = ApiWhopTestRouteImport.update({
  id: '/api/whop-test',
  path: '/api/whop-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUtmifyStripeRoute = ApiPublicUtmifyStripeRouteImport.update({
  id: '/api/public/utmify-stripe',
  path: '/api/public/utmify-stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhopWebhookRoute = ApiPublicWhopWebhookRouteImport.update({
  id: '/api/public/whop-webhook',
  path: '/api/public/whop-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/api/whop-test': typeof ApiWhopTestRoute
  '/api/public/utmify-stripe': typeof ApiPublicUtmifyStripeRoute
  '/api/public/whop-webhook': typeof ApiPublicWhopWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/api/whop-test': typeof ApiWhopTestRoute
  '/api/public/utmify-stripe': typeof ApiPublicUtmifyStripeRoute
  '/api/public/whop-webhook': typeof ApiPublicWhopWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/api/whop-test': typeof ApiWhopTestRoute
  '/api/public/utmify-stripe': typeof ApiPublicUtmifyStripeRoute
  '/api/public/whop-webhook': typeof ApiPublicWhopWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/api/whop-test'
    | '/api/public/utmify-stripe'
    | '/api/public/whop-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/api/whop-test'
    | '/api/public/utmify-stripe'
    | '/api/public/whop-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/api/whop-test'
    | '/api/public/utmify-stripe'
    | '/api/public/whop-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  ApiWhopTestRoute: typeof ApiWhopTestRoute
  ApiPublicUtmifyStripeRoute: typeof ApiPublicUtmifyStripeRoute
  ApiPublicWhopWebhookRoute: typeof ApiPublicWhopWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whop-test': {
      id: '/api/whop-test'
      path: '/api/whop-test'
      fullPath: '/api/whop-test'
      preLoaderRoute: typeof ApiWhopTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/utmify-stripe': {
      id: '/api/public/utmify-stripe'
      path: '/api/public/utmify-stripe'
      fullPath: '/api/public/utmify-stripe'
      preLoaderRoute: typeof ApiPublicUtmifyStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whop-webhook': {
      id: '/api/public/whop-webhook'
      path: '/api/public/whop-webhook'
      fullPath: '/api/public/whop-webhook'
      preLoaderRoute: typeof ApiPublicWhopWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  ApiWhopTestRoute: ApiWhopTestRoute,
  ApiPublicUtmifyStripeRoute: ApiPublicUtmifyStripeRoute,
  ApiPublicWhopWebhookRoute: ApiPublicWhopWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
